name: chatify_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Core Dependencies
  easy_localization: ^3.0.7
  easy_logger: ^0.0.2
  lottie: ^3.1.2
  kartal: ^4.0.4
  auto_route: ^8.3.0 # update this to the latest version while kartal package is updated
  envied: ^0.5.4+1

  # Cache
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0

  # UI Elements
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  auto_route_generator: ^8.1.0 # update this to the latest version while kartal package is updated
  envied_generator: ^0.5.4+1
  flutter_launcher_icons: ^0.13.1

# Generating assets and colors options
flutter_gen:
  output: lib/products/asset/

  integrations:
    lottie: true
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml

# Generate app icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_app.png"
  min_sdk_android: 21 # default 21, android min sdk 16
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/lotties/
    - assets/color/
    - assets/env/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
